version: "3.8"

services:
  app:
    build: .
    container_name: notes-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
